In [1]:
import os
import pandas as pd

In [2]:
data_folder = './data/every5mins/'
assets = ['XAUUSD', 'XAGUSD']

In [22]:
gold = pd.DataFrame()
silver = pd.DataFrame()

price_dict = {}
for f in os.listdir(data_folder):
    # print("==========================================", f)
    asset = f.split('_')[0]
    d = f.split("T")[0].split('_')[-1]#.split("T")[0]
    t = f.split("T")[-1][:-4]
    # print(asset, t)

    ser = pd.read_csv(os.path.join(data_folder, f), index_col=0)['close']
    if d == '2022-08-05':
        ser.name = d
    else:
        ser.name = t

    if asset not in price_dict.keys():
        price_dict[asset] = pd.DataFrame()
    price_dict[asset] = pd.concat([price_dict[asset], ser], axis=1)

In [23]:
tmp = pd.DataFrame()
for asset, df in price_dict.items():
    df.index = pd.to_datetime(df.index)
    tt = df.loc['2022-08-04', :]
    tt.T.name = asset
    tmp = pd.concat([tmp, tt], axis=1)
tmp

            XAGUSD   XAUUSD
20_00_01    20.212  1793.74
20_05_02    20.206  1793.43
20_10_01    20.215  1793.63
20_15_02    20.190  1792.81
20_20_02    20.179  1791.64
20_25_02    20.182  1791.65
20_30_02    20.181  1791.45
20_35_02    20.173  1791.39
20_40_01    20.181  1791.55
20_45_02    20.188  1791.57
20_50_02    20.186  1790.90
20_55_01    20.178  1791.08
21_00_02    20.186  1791.33
21_05_01    20.186  1791.33
21_10_01    20.186  1791.33
21_15_02    20.186  1791.33
21_20_01    20.186  1791.33
21_25_02    20.186  1791.33
21_30_01    20.186  1791.33
21_35_02    20.186  1791.33
21_40_01    20.186  1791.33
21_45_02    20.186  1791.33
21_50_01    20.186  1791.33
21_55_02    20.186  1791.33
22_00_01    20.194  1791.33
22_05_02    20.206  1790.79
22_10_02    20.197  1790.54
22_15_02    20.179  1790.35
22_20_02    20.175  1790.01
22_25_02    20.173  1790.19
22_30_01    20.179  1790.15
22_35_02    20.182  1790.37
23_40_02    20.202  1792.56
23_45_01    20.200  1792.87
23_50_02    20.195  1792.46
23_55_01    20.211  1793.63
2022-08-05  20.203  1793.43